### ISSUE TITLE
Adding own proxies.

### ISSUE THREAD

**Issue by santacl4ws** [popohet/strawpoll-bot#3]
How do i add my own proxies?
I have tried edditing proxy_list.json but have no luck.

**Comment by popohet** [comment]
did you disable the "Automatically get proxies?" option ?

> go to your terminal
> run the script
> choose "Configurate"
> choose "False"

go to https://shancarter.github.io/mr-data-converter/
paste your proxies there and choose the "JSON - Row Arrays" option. Now put it at proxy_list.json

let me know if you get any error.
